# MinGW-w64 x86_64 toolchain for cross-compiling Windows binaries on Linux

set(MINGW_PREFIX x86_64-w64-mingw32- CACHE STRING "Prefix in MinGW binaries")
set(MINGW_ROOT /usr/x86_64-w64-mingw32 CACHE STRING "Full path to MinGW root directory")

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER    ${MINGW_PREFIX}gcc)
set(CMAKE_CXX_COMPILER  ${MINGW_PREFIX}g++)
set(CMAKE_RC_COMPILER   ${MINGW_PREFIX}windres)

set(CMAKE_FIND_ROOT_PATH ${MINGW_ROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
